apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fortstak-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/AbdElRhmanArafa/FortStak.git
    targetRevision: HEAD
    path: Part3
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
