apiVersion: apps/v1
kind: Deployment
metadata:
  name: fortstak-deployment
  namespace: default
  labels:
    app: fortstak
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fortstak
  template:
    metadata:
      labels:
        app: fortstak
    spec:
      imagePullSecrets:
      - name: fortstak-registry-secret
      containers:
      - name: fortstak
        image: abdelrahman2arafa/fortstak:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 4000
          name: http
        readinessProbe:
          httpGet:
            path: /
            port: 4000
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /
            port: 4000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: fortstak-service
  namespace: default
  labels:
    app: fortstak
spec:
  type: NodePort
  selector:
    app: fortstak
  ports:
  - port: 80
    targetPort: 4000
    nodePort: 30080
    protocol: TCP
    name: http
