name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  release:
    types: [created]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image (local, not pushed)
        uses: docker/build-push-action@v5
        with:
          context: ./Part1
          file: ./Part1/DockerFile
          push: false
          tags: fortstak:latest

      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@v0.14.0
        with:
          image-ref: fortstak:latest
          format: table
          exit-code: 1
          ignore-unfixed: true

      - name: Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./Part1
          file: ./Part1/DockerFile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/fortstak:latest
